"""update in  document table

Revision ID: e57a7f52cdd4
Revises: 4b929c898ae4
Create Date: 2026-08-22 12:09:08.982012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57a7f52cdd4'
down_revision: Union[str, Sequence[str], None] = '4b929c898ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('s3_key', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_documents_s3_key'), 'documents', ['s3_key'], unique=False)
    op.drop_column('documents', 'path')
    op.drop_column('documents', 'pages')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'ready'::character varying"), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('pages', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_documents_s3_key'), table_name='documents')
    op.drop_column('documents', 's3_key')
    # ### end Alembic commands ###
